import os
from typing import Optional, List
from ..schemas import GrowthPlan

class EmailNotifier:
    """Sends growth plan notifications via email"""
    
    def __init__(self):
        self.api_key = os.getenv("SENDGRID_API_KEY")
        self.from_email = os.getenv("EMAIL_FROM", "noreply@growthcopilot.com")
        self.enabled = os.getenv("EMAIL_NOTIFICATIONS_ENABLED", "false").lower() == "true"
        self.test_mode = os.getenv("EMAIL_TEST_MODE", "true").lower() == "true"
        
        # Only import SendGrid if not in test mode
        if not self.test_mode and self.api_key:
            try:
                from sendgrid import SendGridAPIClient
                from sendgrid.helpers.mail import Mail
                self.client = SendGridAPIClient(self.api_key)
                self.Mail = Mail
            except ImportError:
                print("⚠️ sendgrid not installed, using test mode")
                self.test_mode = True
        else:
            self.client = None
    
    def send_plan_email(
        self, 
        plan: GrowthPlan, 
        trace_id: str,
        to_emails: List[str]
    ) -> bool:
        """
        Send a growth plan via email
        
        Args:
            plan: The generated growth plan
            trace_id: Unique trace ID for this plan
            to_emails: List of recipient email addresses
            
        Returns:
            True if sent successfully, False otherwise
        """
        if not self.enabled:
            return False
        
        if not to_emails:
            print("⚠️ No recipient emails provided")
            return False
        
        # Build email content
        subject = f"🚀 New Growth Plan: {plan.business_profile.name}"
        html_content = self._build_html_email(plan, trace_id)
        text_content = self._build_text_email(plan, trace_id)
        
        # Test mode - just print to console
        if self.test_mode:
            print("\n" + "="*60)
            print("📧 EMAIL NOTIFICATION (TEST MODE)")
            print("="*60)
            print(f"From: {self.from_email}")
            print(f"To: {', '.join(to_emails)}")
            print(f"Subject: {subject}")
            print("\n--- EMAIL CONTENT (Text Version) ---")
            print(text_content)
            print("="*60)
            print("✅ Email sent (test mode)\n")
            return True
        
        # Real mode - send via SendGrid
        try:
            for to_email in to_emails:
                message = self.Mail(
                    from_email=self.from_email,
                    to_emails=to_email,
                    subject=subject,
                    html_content=html_content,
                    plain_text_content=text_content
                )
                
                response = self.client.send(message)
                
                if response.status_code in [200, 202]:
                    print(f"✅ Email sent to {to_email} for trace {trace_id}")
                else:
                    print(f"⚠️ Email failed to {to_email}: {response.status_code}")
                    return False
            
            return True
                
        except Exception as e:
            print(f"❌ Email error: {e}")
            return False
    
    def _build_text_email(self, plan: GrowthPlan, trace_id: str) -> str:
        """Build plain text email content"""
        
        # Calculate revenue opportunity
        revenue_opp = plan.kpis.revenue * (1 / (1 - plan.funnel_insight.drop_rate) - 1)
        
        text = f"""
Growth Plan for {plan.business_profile.name}
{'='*60}

BUSINESS INFO
Industry: {plan.business_profile.industry}
Region: {plan.business_profile.region}
Goal: {plan.goal.objective}
Timeframe: {plan.goal.horizon_weeks} weeks

FUNNEL ANALYSIS
Bottleneck: {plan.funnel_insight.from_step} → {plan.funnel_insight.to_step}
Drop Rate: {plan.funnel_insight.drop_rate*100:.1f}%
Revenue Opportunity: ${revenue_opp:,.2f}

RECOMMENDED EXPERIMENT
Name: {plan.chosen_experiment.experiment.name}
Channel: {plan.chosen_experiment.experiment.channel}
Priority Score: {plan.chosen_experiment.priority_score:.1f}
  - Impact: {plan.chosen_experiment.impact}
  - Confidence: {plan.chosen_experiment.confidence}
  - Effort: {plan.chosen_experiment.effort}

Hypothesis: {plan.chosen_experiment.experiment.hypothesis}

ALL EXPERIMENTS EVALUATED ({len(plan.experiments)}):
"""
        
        for i, exp in enumerate(plan.experiments[:5], 1):
            text += f"{i}. {exp.experiment.name} (Score: {exp.priority_score:.1f})\n"
        
        if plan.llm_strategy_commentary:
            text += f"\nAI STRATEGY COMMENTARY:\n{plan.llm_strategy_commentary[:300]}...\n"
        
        text += f"\nTrace ID: {trace_id}\n"
        text += f"Generated by SME Growth Co-Pilot\n"
        text += "="*60
        
        return text
    
    def _build_html_email(self, plan: GrowthPlan, trace_id: str) -> str:
        """Build HTML email content"""
        
        # Calculate revenue opportunity
        revenue_opp = plan.kpis.revenue * (1 / (1 - plan.funnel_insight.drop_rate) - 1)
        
        # Build experiments list
        experiments_html = ""
        for i, exp in enumerate(plan.experiments[:5], 1):
            experiments_html += f"""
            <tr>
                <td style="padding: 8px; border-bottom: 1px solid #eee;">
                    {i}. {exp.experiment.name}
                </td>
                <td style="padding: 8px; border-bottom: 1px solid #eee; text-align: right;">
                    <strong>{exp.priority_score:.1f}</strong>
                </td>
            </tr>
            """
        
        html = f"""
        <!DOCTYPE html>
        <html>
        <head>
            <meta charset="utf-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
        </head>
        <body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; padding: 20px;">
            
            <div style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); padding: 30px; border-radius: 10px 10px 0 0; text-align: center;">
                <h1 style="color: white; margin: 0;">🚀 New Growth Plan</h1>
                <p style="color: white; margin: 10px 0 0 0; font-size: 18px;">{plan.business_profile.name}</p>
            </div>
            
            <div style="background: #f9f9f9; padding: 30px; border-radius: 0 0 10px 10px;">
                
                <div style="background: white; padding: 20px; border-radius: 8px; margin-bottom: 20px; border-left: 4px solid #667eea;">
                    <h2 style="margin-top: 0; color: #667eea;">📊 Business Overview</h2>
                    <table style="width: 100%;">
                        <tr>
                            <td style="padding: 5px;"><strong>Industry:</strong></td>
                            <td style="padding: 5px;">{plan.business_profile.industry}</td>
                        </tr>
                        <tr>
                            <td style="padding: 5px;"><strong>Region:</strong></td>
                            <td style="padding: 5px;">{plan.business_profile.region}</td>
                        </tr>
                        <tr>
                            <td style="padding: 5px;"><strong>Goal:</strong></td>
                            <td style="padding: 5px;">{plan.goal.objective}</td>
                        </tr>
                        <tr>
                            <td style="padding: 5px;"><strong>Timeframe:</strong></td>
                            <td style="padding: 5px;">{plan.goal.horizon_weeks} weeks</td>
                        </tr>
                    </table>
                </div>
                
                <div style="background: white; padding: 20px; border-radius: 8px; margin-bottom: 20px; border-left: 4px solid #f59e0b;">
                    <h2 style="margin-top: 0; color: #f59e0b;">🔍 Funnel Bottleneck</h2>
                    <p style="font-size: 16px;">
                        Biggest drop: <strong>{plan.funnel_insight.from_step}</strong> → <strong>{plan.funnel_insight.to_step}</strong><br>
                        Drop rate: <strong style="color: #ef4444;">{plan.funnel_insight.drop_rate*100:.1f}%</strong>
                    </p>
                    <div style="background: #fef3c7; padding: 15px; border-radius: 6px; margin-top: 10px;">
                        <p style="margin: 0; font-size: 18px; color: #92400e;">
                            💰 <strong>Revenue Opportunity: ${revenue_opp:,.2f}</strong>
                        </p>
                    </div>
                </div>
                
                <div style="background: white; padding: 20px; border-radius: 8px; margin-bottom: 20px; border-left: 4px solid #10b981;">
                    <h2 style="margin-top: 0; color: #10b981;">🎯 Recommended Experiment</h2>
                    <h3 style="color: #333; margin: 10px 0;">{plan.chosen_experiment.experiment.name}</h3>
                    <p style="margin: 5px 0;"><strong>Channel:</strong> {plan.chosen_experiment.experiment.channel}</p>
                    <p style="margin: 5px 0;">
                        <strong>Priority Score:</strong> {plan.chosen_experiment.priority_score:.1f}
                        (Impact: {plan.chosen_experiment.impact} | 
                        Confidence: {plan.chosen_experiment.confidence} | 
                        Effort: {plan.chosen_experiment.effort})
                    </p>
                    <p style="margin-top: 15px; padding: 15px; background: #f0fdf4; border-radius: 6px; font-style: italic;">
                        "{plan.chosen_experiment.experiment.hypothesis}"
                    </p>
                </div>
                
                <div style="background: white; padding: 20px; border-radius: 8px; margin-bottom: 20px;">
                    <h2 style="margin-top: 0; color: #667eea;">📋 All Experiments Evaluated</h2>
                    <table style="width: 100%; border-collapse: collapse;">
                        {experiments_html}
                    </table>
                </div>
                
                <div style="text-align: center; padding: 20px; color: #666; font-size: 12px;">
                    <p>Trace ID: {trace_id} | Generated by SME Growth Co-Pilot</p>
                </div>
                
            </div>
            
        </body>
        </html>
        """
        
        return html


# Singleton instance
email_notifier = EmailNotifier()